	nolist
; ---------------------------
DOTC_CONSTANTS_I	equ 1
DOTC_MACROS_I		equ 1
LINK_I			equ 1
GENERATE_LOADMAIN	equ 1
GENERATE_BINEXE		equ 1
; ---------------------------
	IF GENERATE_LOADMAIN

	read "DoTC.asm"
;;	read "DoTC_Loader.asm"

	ENDIF
; ---------------------------
	IF GENERATE_BINEXE

	read "DoTC_Defeat.asm"
	read "DoTC_Event.asm"
	read "DoTC_Intro.asm"
	read "DoTC_Joust.asm"
	read "DoTC_Raid.asm"
	read "DoTC_Robin.asm"
	read "DoTC_MusInt.asm"
	read "DoTC_Siege.asm"
	read "DoTC_Victory.asm"

	ENDIF

;	read "DoTC_Sound_Manager.asm"
; ------------------------------------------------------------------------------
; Generate data file
; ------------------------------------------------------------------------------
; Generate colors+screen
; ---------------------------
; .SCP = compacted screen with Exomizer 2.0.3

SAVE_SCREEN	equ 0
SAVE_SPRITE	equ 0
TOTO		equ 0

SCREEN_START	equ &4000

	IF TOTO

	MACRO SAVE_SCREEN_DEF FILENAME

	org SCREEN_START
	write "TOTO/FILENAME.DEF"
	dw FILENAME
	incbin "TOTO/FILENAME.PAL"

	incbin "TOTO/FILENAME.SCR.SCP"

LET FILENAME = $-SCREEN_START

	ENDM

	SAVE_SCREEN_DEF TITLE
	SAVE_SCREEN_DEF TRUMP

	ENDIF

	IF SAVE_SCREEN

	MACRO SAVE_SCREEN_DEF FILENAME

	org SCREEN_START
	write "DEF/FILENAME.DEF"
	dw FILENAME
	incbin "DEF/Original_Screen/FILENAME.PAL"

	incbin "DEF/Original_Screen/FILENAME.SCR.SCP"

LET FILENAME = $-SCREEN_START

	ENDM

	SAVE_SCREEN_DEF BATBACK
	SAVE_SCREEN_DEF BEDROOM
	SAVE_SCREEN_DEF COURT
	SAVE_SCREEN_DEF CROWNING
	SAVE_SCREEN_DEF GALLERY
	SAVE_SCREEN_DEF INTERIOR
	SAVE_SCREEN_DEF JOUSTOP
	SAVE_SCREEN_DEF NAMES
	SAVE_SCREEN_DEF NCASTLE
	SAVE_SCREEN_DEF NORMLONG
	SAVE_SCREEN_DEF PLOTTERS
	SAVE_SCREEN_DEF ROOMWALL
	SAVE_SCREEN_DEF SAXLONG
	SAVE_SCREEN_DEF SCASTLE
	SAVE_SCREEN_DEF SIDE
	SAVE_SCREEN_DEF TACTMAP
	SAVE_SCREEN_DEF TENTS
	SAVE_SCREEN_DEF TITLE
	SAVE_SCREEN_DEF TRUMP

	ENDIF


	MACRO SAVE_SPRITE_DEF FILENAME

	org SCREEN_START
	write "SPR/FILENAME.SPR"
	dw FILENAME
	incbin "SPR/Original_SPR/FILENAME.SPR"

FILENAME equ $-SCREEN_START

	ENDM

	IF SAVE_SPRITE

	SAVE_SPRITE_DEF BATSPR
	SAVE_SPRITE_DEF BISOU1
	SAVE_SPRITE_DEF BISOU2
	SAVE_SPRITE_DEF BISOU3
	SAVE_SPRITE_DEF BLONDE
	SAVE_SPRITE_DEF BRUNE
	SAVE_SPRITE_DEF CATANIM
	SAVE_SPRITE_DEF CATSPR
	SAVE_SPRITE_DEF CHARGE
	SAVE_SPRITE_DEF COUPLE1
	SAVE_SPRITE_DEF COUPLE2
	SAVE_SPRITE_DEF COUPLE3
	SAVE_SPRITE_DEF COUPLE4
	SAVE_SPRITE_DEF COUPLE5
	SAVE_SPRITE_DEF ENDSPR

	org SCREEN_START
	write "SPR/FACES.SPR"
;	dw FILENAME_LENGTH -> added to TACTSPR, no length necessary !
	incbin "SPR/Original_SPR/FACES.SPR"

	SAVE_SPRITE_DEF FIGHTERS
	SAVE_SPRITE_DEF FIRE
	SAVE_SPRITE_DEF GKNIGHT
	SAVE_SPRITE_DEF JTOPSPR
	SAVE_SPRITE_DEF MCATSPR
	SAVE_SPRITE_DEF SIDEDEAD
	SAVE_SPRITE_DEF SIDELOST
	SAVE_SPRITE_DEF SIDEWON
	SAVE_SPRITE_DEF SPRSIEGE

list

	SAVE_SPRITE_DEF TACTSPR

	ENDIF

	END